"""unique completion per day

Revision ID: 33eab78781a6
Revises: 15c3c1826ac0
Create Date: 2026-01-09 21:22:56.509630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eab78781a6'
down_revision: Union[str, Sequence[str], None] = '15c3c1826ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    # ### end Alembic commands ###
