"""add user_id to habit

Revision ID: 61b0e93271cd
Revises: 463b5371865f
Create Date: 2026-06-28 22:17:01.732452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b0e93271cd'
down_revision: Union[str, Sequence[str], None] = '463b5371865f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_column('habits', 'user_id')
    # ### end Alembic commands ###
