"""unique completion per habit per day

Revision ID: 895c793c11ff
Revises: 33eab78781a6
Create Date: 2026-01-09 21:30:06.751588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895c793c11ff'
down_revision: Union[str, Sequence[str], None] = '33eab78781a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_completion_habit_day', 'habit_completions', ['habit_id', 'done_on'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_completion_habit_day', 'habit_completions', type_='unique')
    # ### end Alembic commands ###
